export const TEAM_MEMBERS = [
  {
    id: "1",
    name: "Rachel Onyango | Founder & CEO",
    designation: "Sociologist, Counselor & Community Development Specialist",
    socialMedia: "https://www.linkedin.com/in/",
    imageUrl: "/images/volunteers/rachael-onyango.jpg",
    testimonial:
      "Rachel Achieng Onyango is a dynamic development leader with over a decade of experience in strategic leadership, organizational development, and partnership management within Kenya's nonprofit and social impact sectors. As Director at Thrive from Thrones, she provides visionary oversight, driving sustainable community transformation through evidence-based programming, innovation, and stakeholder engagement.\n\nRachel currently serves as Country Director at Christ's Hope International Kenya, where she leads a multidisciplinary team delivering child development, health, and economic empowerment programs. Under her leadership, the organization has strengthened systems, expanded fundraising networks, enhanced program quality, and deepened impact across vulnerable communities.\n\nShe is also the Managing Partner at SCRIDE Consulting Agency, where she supports organizations with strategic planning, training, monitoring and evaluation, and change management. Her earlier role as Project Director at Compassion International saw her oversee child survival and development programs for over 1,000 children, coordinating donor engagement, community mobilization, and family strengthening initiatives. In addition, she has worked with Youth Alive! Kenya, Farmers Voice Radio and Kenya Red Cross Society.\n\nRachel holds a bachelor's degree in Sociology with IT from Maseno University and is currently pursuing a Master's in Social Development and Management. She has completed advanced professional training in monitoring and evaluation, leadership and management, biblical counseling, and child development.\n\nHer core strengths include program design and delivery, strategic fundraising, stakeholder relations, team leadership, and safeguarding. Rachel is known for cultivating high-performing teams, championing ethical governance, and fostering inclusive, purpose-driven impact. As Director at Thrive from Thrones, Rachel brings a wealth of experience, a heart for community resilience, and a strategic mindset focused on advancing holistic development and long-term sustainability.",
  },

  {
    id: "3",
    name: "CPA Sharon Omondi | Board Treasurer",
    designation: "Finance Administrator | Certified Public Accountant",
    socialMedia: "https://www.linkedin.com/in/",
    imageUrl: "/images/volunteers/sharon-omondi.jpg",
    testimonial:
      "Sharon Omondi, CPA-K is a seasoned finance professional and governance leader with extensive experience in accounting, financial management, and nonprofit financial stewardship. As Board Treasurer at Thrive from Thorns, she provides strategic financial oversight, fiduciary leadership, and accountability systems that safeguard the organization's resources and ensure alignment with its mission of restoring individuals and communities to dignity, strength, and purpose.\n\nSharon brings strong expertise in financial governance, compliance, budgeting, and internal controls, supporting the Board and management to make sound, data-driven decisions. In her role as Treasurer, she oversees financial planning, financial reporting, risk management, and audit processes, ensuring transparency and sustainability across the organization's programs and operations.\n\nShe is a Certified Public Accountant (CPA-K) with a professional background spanning corporate finance, consulting, and advisory services. Sharon has worked with organizations and enterprises to strengthen financial systems, improve compliance, and enhance financial literacy and empowerment. Her experience enables her to translate complex financial information into clear insights for leadership and governance bodies.\n\nSharon is also engaged in financial empowerment and advisory initiatives, supporting individuals, small businesses, and community organizations to build strong financial foundations. Her work is grounded in professionalism, integrity, and a commitment to ethical stewardship.\n\nAs Board Treasurer of Thrive from Thorns, Sharon Omondi brings disciplined financial leadership, strong governance acumen, and a passion for accountability—ensuring that the organization's resources are managed with excellence and integrity to advance long-term impact and mission sustainability.",
  },

  {
    id: "4",
    name: "Duncan Ouma Okuru | Board Member",
    designation: "Economist & Entrepreneurship Expert",
    socialMedia: "https://www.linkedin.com/in/",
    imageUrl: "/images/volunteers/duncan-okuro.jpg",
    testimonial:
      "Duncan Ouma Okuro is a seasoned development practitioner with over eight years of experience in designing, leading, and managing community-focused economic empowerment, entrepreneurship, and inclusion programs in Kenya. His work spans refugees and host communities, microfinance, youth development, and nonprofit operations.\n\nDuncan currently serves as the Economic Inclusion Program Manager at HIAS Refugee Trust of Kenya, where he leads strategy, implementation, and partnerships for programs that enhance access to livelihoods, financial education, vocational training, and job opportunities. He manages multi-stakeholder relationships, donor proposals, and operational risk, ensuring that programs are efficient, sustainable, and responsive to community needs.\n\nEarlier in his career, he coordinated entrepreneurship development and savings groups at CAP Youth Empowerment Institute along Kenya's coast, directed income-generating and women empowerment programs with COHAT in Nairobi's informal settlements, and worked in microfinance at SISDO and Speed Capital, where he developed skills in loan management, portfolio quality, and client relationship building.\n\nDuncan holds an MBA in Project Management from Kenyatta University, a Bachelor of Arts in Economics & Business Studies with IT from Maseno University, and a Certificate in Project Management from the European Business University of Luxembourg. He has also undertaken professional training in facilitation, business development, financial literacy, and monitoring & evaluation.\n\nAs a Board Member at Thrive from Thrones, Duncan brings strong technical expertise, operational rigour, a results-driven mindset, and a passion for inclusive, sustainable development. He helps anchor the organization's work in economic justice, innovation, and community ownership.",
  },

  {
    id: "5",
    name: "Moses Sadia | Board Member",
    designation: "Clinical Health Practitioner & Public Health Expert",
    socialMedia: "https://www.linkedin.com/in/",
    imageUrl: "/images/volunteers/sadia-moses.jpg",
    testimonial:
      "Moses Omondi Sadia is a seasoned clinician, epidemiologist, and public health leader with over 13 years of experience advancing health systems, community health, and implementation science across Kenya. His work spans grassroots health programming, national policy implementation, academic teaching, and applied public health research.\n\nMoses has led USAID-funded malaria and integrated disease surveillance projects across multiple counties, managing complex teams and budgets exceeding $1 million. He previously led large-scale community health initiatives at Lwala Community Alliance, impacting over 1.2 million people and spearheading the rollout of Kenya's Electronic Community Health Information System (eCHIS)—a flagship digital health reform under the Ministry of Health.\n\nMoses holds a Master of Science in Epidemiology and Biostatistics, a Bachelor of Science in Public Health, and a Diploma in Clinical Medicine & Surgery. He is currently pursuing a Ph.D. in Public Health. He has served as Principal Investigator and Co-Principal Investigator on multi-county operational and implementation research studies, including therapeutic efficacy studies for malaria, severe malaria case reviews, and health systems evaluations.\n\nHis scholarly contributions include publications in peer-reviewed journals covering vaccine hesitancy, child nutrition, immunization, and malaria interventions. As a part-time lecturer at several Kenyan universities, he contributes to building public health capacity through teaching and mentorship.\n\nMoses has worked with a wide range of development partners—including USAID, PMI, Jhpiego, KEMRI, and Harvard University—offering technical leadership in maternal and child health, epidemiology, community systems strengthening, and monitoring and evaluation.\n\nAs a Board Member at Thrive for Thorns, Moses brings deep technical expertise, strategic insight, and a strong commitment to evidence-based health interventions that drive sustainable, inclusive development at both community and systems levels.",
  },
];
