export const TEAM_MEMBERS = [
  {
    id: "1",
    name: "Rachel Onyango | Founder & CEO",
    designation: "Sociologist, Counselor & Community Development Specialist",
    socialMedia: "https://www.linkedin.com/in/",
    imageUrl: "/images/volunteers/rachael-onyango.jpg",
    testimonial:
      "Rachel Achieng Onyango is a dynamic development leader with over a decade of experience in strategic leadership, organizational development, and partnership management within Kenya’s nonprofit and social impact sectors. As Director at Thrive from Thrones, she provides visionary oversight, driving sustainable community transformation through evidence-based programming, innovation, and stakeholder engagement. Rachel currently serves as Country Director at Christ’s Hope International Kenya, where she leads a multidisciplinary team delivering child development, health, and economic empowerment programs. Under her leadership, the organization has strengthened systems, expanded fundraising networks, enhanced program quality, and deepened impact across vulnerable communities. She is also the Managing Partner at SCRIDE Consulting Agency, where she supports organizations with strategic planning, training, monitoring and evaluation, and change management. Her earlier role as Project Director at Compassion International saw her oversee child survival and development programs for over 1,000 children, coordinating donor engagement, community mobilization, and family strengthening initiatives. In addition, she has worked with Youth Alive! Kenya, Farmers Voice Radio and Kenya Red Cross Society Rachel holds a bachelor’s degree in Sociology with IT from Maseno University and is currently pursuing a Master’s in Social Development and Management. She has completed advanced professional training in monitoring and evaluation, leadership and management, biblical counseling, and child development. Her core strengths include program design and delivery, strategic fundraising, stakeholder relations, team leadership, and safeguarding. Rachel is known for cultivating high-performing teams, championing ethical governance, and fostering inclusive, purpose-driven impact. As Director at Thrive from Thrones, Rachel brings a wealth of experience, a heart for community resilience, and a strategic mindset focused on advancing holistic development and long-term sustainability.",
  },
  
  {
    id: "3",
    name: "CPA Sharon Omondi | Board Treasurer",
    designation: "Finance Administrator | Certified Public Accountant",
    socialMedia: "https://www.linkedin.com/in/",
    imageUrl: "/images/volunteers/sharon-omondi.jpg",
    testimonial:
      "Sharon Omondi is a seasoned finance professional and Certified Public Accountant with over 15 years of experience in financial management, risk assessment, governance, and donor compliance within the nonprofit and development sectors. As Board Treasurer at Thrive from Thrones, she provides strategic oversight on financial stewardship, institutional accountability, and organizational sustainability. Sharon currently serves as the Head of Internal Audit & Risk at Plan International Kenya, where she leads the internal control framework, risk management strategy, and compliance audits for multimillion-dollar programs across the country. Her work ensures that donor funds are well managed, systems are transparent, and programs meet the highest standards of fiduciary responsibility. Previously, Sharon held finance and audit roles at global and national organizations, where she contributed to systems strengthening, financial policy development, and capacity building for teams managing grants from donors such as USAID, DFID, and the EU. She holds a Bachelor of Commerce in Finance from Kenyatta University and is a member of the Institute of Certified Public Accountants of Kenya (ICPAK). She has also undertaken specialized training in enterprise risk management, fraud prevention, and financial strategy for nonprofit organizations. As a board member at Thrive from Thrones, Sharon brings financial acumen, governance insight, and a strong commitment to transparency and ethical leadership. Her guidance ensures that the organization’s resources are used effectively to support grassroots transformation and sustainable impact.",
  },
  {
    id: "4",
    name: "Duncan Ouma Okuru | Board Member",
    designation: "Economist & Entrepreneurship Expert",
    socialMedia: "https://www.linkedin.com/in/",
    imageUrl: "/images/volunteers/duncan-okuro.jpg",
    testimonial:
      "Duncan Ouma Okuro is a seasoned development practitioner with over eight years of experience in designing, leading, and managing community-focused economic empowerment, entrepreneurship, and inclusion programs in Kenya. His work spans refugees and host communities, microfinance, youth development, and nonprofit operations. Duncan currently serves as the Economic Inclusion Program Manager at HIAS Refugee Trust of Kenya, where he leads strategy, implementation, and partnerships for programs that enhance access to livelihoods, financial education, vocational training, and job opportunities. He manages multi-stakeholder relationships, donor proposals, and operational risk, ensuring that programs are efficient, sustainable, and responsive to community needs. Earlier in his career, he coordinated entrepreneurship development and savings groups at CAP Youth Empowerment Institute along Kenya’s coast, directed income-generating and women empowerment programs with COHAT in Nairobi’s informal settlements, and worked in microfinance at SISDO and Speed Capital, where he developed skills in loan management, portfolio quality, and client relationship building. Duncan holds an MBA in Project Management from Kenyatta University, a Bachelor of Arts in Economics & Business Studies with IT from Maseno University, and a Certificate in Project Management from the European Business University of Luxembourg. He has also undertaken professional training in facilitation, business development, financial literacy, and monitoring & evaluation. As a Board Member at Thrive from Thrones, Duncan brings strong technical expertise, operational rigour, a results-driven mindset, and a passion for inclusive, sustainable development. He helps anchor the organization’s work in economic justice, innovation, and community ownership.",
  },

  {
    id: "5",
    name: "Moses Sadia |  Board Member",
    designation: "Clinical Health Practitioner & Public Health Expert",
    socialMedia: "https://www.linkedin.com/in/",
    imageUrl: "/images/volunteers/sadia-moses.jpg",
    testimonial:
      "Moses Omondi Sadia is a seasoned clinician, epidemiologist, and public health leader with over 13 years of experience advancing health systems, community health, and implementation science across Kenya. His work spans grassroots health programming, national policy implementation, academic teaching, and applied public health research. Moses has led USAID-funded malaria and integrated disease surveillance projects across multiple counties, managing complex teams and budgets exceeding $1 million. He previously led large-scale community health initiatives at Lwala Community Alliance, impacting over 1.2 million people and spearheading the rollout of Kenya’s Electronic Community Health Information System (eCHIS)—a flagship digital health reform under the Ministry of Health. Moses holds a Master of Science in Epidemiology and Biostatistics, a Bachelor of Science in Public Health, and a Diploma in Clinical Medicine & Surgery. He is currently pursuing a Ph.D. in Public Health. He has served as Principal Investigator and Co-Principal Investigator on multi-county operational and implementation research studies, including therapeutic efficacy studies for malaria, severe malaria case reviews, and health systems evaluations. His scholarly contributions include publications in peer-reviewed journals covering vaccine hesitancy, child nutrition, immunization, and malaria interventions. As a part-time lecturer at several Kenyan universities, he contributes to building public health capacity through teaching and mentorship. Moses has worked with a wide range of development partners—including USAID, PMI, Jhpiego, KEMRI, and Harvard University—offering technical leadership in maternal and child health, epidemiology, community systems strengthening, and monitoring and evaluation. As a Board Member at Thrive for Thorns, Moses brings deep technical expertise, strategic insight, and a strong commitment to evidence-based health interventions that drive sustainable, inclusive development at both community and systems levels.",
  },
  

];
